image: python:3.12

stages:
  - build

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - pip list
    - python -m PyInstaller main.py  --name $PROGRAM_NAME --hidden-import=_cffi_backend -F --clean --strip
    - du -sh dist/igem-upload
  artifacts:
    paths:
      - dist/igem-upload
