image: python:3.12

stages:
  - build

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - bash setup.sh build 
    - mv dist/* ./
    - du -sh dist/
  artifacts:
    paths:
      - igem-cdn
