name: Build Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12"]
        architecture: [x86_64, arm64]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build with PyInstaller
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          CFLAGS="-arch ${{ matrix.architecture }}" LDFLAGS="-arch ${{ matrix.architecture }}" bash setup.sh build
        else
          bash setup.sh build
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}-${{ matrix.architecture }}
        path: dist/
